spring:
	profiles:
		active:
		- dev

-----
spring:
	profiles: dev #开发环境
	application:
		name: hellospringcloud-config-dev

----
spring:
	profiles: test   #测试环境
	application:
		name: hellospringcloud-config-test

#保存为utf-8
