spring:
  application:
    name: eureka-client-user
  datasource:
    url: jdbc:mysql://localhost/java_web?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#Mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: hellospringcloud

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: hellospringcloud-user8008-hystrix
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8008
